version: "3.9"

services:
  aqua_pprof_postgres:
    container_name: aqua_pprof_postgres
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: aqua_pprof_database
      POSTGRES_USER: aqua_pprof_username
      POSTGRES_PASSWORD: aqua_pprof_password